logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: TRACE

spring:
  data:
    mongo:
      authentication-database: admin
    username: rootuser
    password: rootpass
    database: streaming
    port: 27017
    host: localhost

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  tomcat:
    max-http-post-size: 1000000000
    max-swallow-size: 1000000000

pl:
  agh:
    iet:
      ffmpeg:
        path: "C:\\ffmpeg-n4.4-latest-win64-gpl-4.4\\bin\\ffmpeg.exe"
        probe: "C:\\ffmpeg-n4.4-latest-win64-gpl-4.4\\bin\\ffprobe.exe"
        output-dir: "C:\\Users\\owasi\\OneDrive\\Pulpit\\streaming-api-backend\\src\\main\\resources\\streams\\"
        server-url: http://localhost:8080/streaming-api/
      thumbnail:
        path: "C:\\Users\\owasi\\OneDrive\\Pulpit\\streaming-api-backend\\src\\main\\resources\\thumbnails\\"