logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: TRACE
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
            repository:
              query: DEBUG

spring:
  data:
    mongo:
      authentication-database: admin
      auth-source: admin
    username: user
    password: pass
    database: streaming
    port: 27017
    host: localhost

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

server:
  tomcat:
    max-http-post-size: 2000000000
    max-swallow-size: 2000000000

pl:
  agh:
    iet:
      ffmpeg:
        path: "C:\\ffmpeg-n4.4-latest-win64-gpl-4.4\\bin\\ffmpeg.exe"
        probe: "C:\\ffmpeg-n4.4-latest-win64-gpl-4.4\\bin\\ffprobe.exe"
        output-dir: "C:\\Users\\owasi\\OneDrive\\Pulpit\\streaming-api-backend\\src\\main\\resources\\streams\\"
        server-url: http://localhost:8080/streaming-api/
      thumbnail:
        path: "C:\\Users\\owasi\\OneDrive\\Pulpit\\streaming-api-backend\\src\\main\\resources\\thumbnails\\"